### PR TITLE
Make wrapper for LibreOffice an extension

### PR DESCRIPTION
**Pull request by spinnau**
### Description of the change

The LibreOffice wrapper is changed to be a real extension for LibreOffice. Just as with the current solution, Python is used for the calculations in the background.

The directory of the wrapper contains a Readme file with instructions for building and installing the extension. The Web documentation is also updated to reflect the changes.

### Benefits

* The extension contains the complete wrapper code. Thus, there is no need anymore to use a special prepared LibreOffice template file. The CoolProp functions should work in any LibreOffice spreadsheet file.

* The extension is enhanced to wrap all high-level interface functions:
  - PropsSI
  - Props1SI
  - PhaseSI
  - HAPropsSI
  - get_fluid_param_string
  - get_global_param_string

* The extension includes a description for all CoolProp functions and their parameters. The descriptions are visible when a CoolProp function is entered as a cell formula directly or with the function wizard. (In principle it would also be easy to integrate translation strings for this.)

* Installing the extension itself is as easy as double-clicking on the downloaded oxt-file. To make the installation of the Python package more easy, a helper function is included, that downloads and extracts the wheel file into the extension directory. This install function can easily be called from the LibreOffice options menu. Unfortunately, Python interpreters bundled with LibreOffice doesn't include pip. Thus, I have created a simple function to check the platform and download the appropriate wheel from PyPI. It's implemented in `wrappers/LibreOffice/src/scripts/scripts.py`

### Verification Process

I have tested the LibreOffice extension including the Python package download function on these platforms:

* LO 6.1.4.2 64bit, Arch Linux, Python 3.7.1
* LO 6.1.4.2 32bit, Windows 7, Python 3.5.5 (bundled with LO)
* LO 6.1.4.2 64bit, macOS Sierra 10.12.6, Python 3.5.5 (bundled with LO)
* LO 5.2.7.2 64bit, Chrome OS + crostini (Debian Stretch amd64), Python 3.5.3

### Discussion

* Tests were successful on several platforms. ~~I have marked the PR as WIP. From my point of view it's working and ready to merge. But maybe somebody can test the extension and Python package installation routine on other platforms (Mac?) before merging.~~

* LibreOffice switched to Python 3 since version 4.0. Thus, I think it's fine not to test with Python 2.

* The LibreOffice extensions can now be built with CMake using the global version number. ~~By now the CoolProp version is manually added to the makefile of the wrapper. This could be changed to use the version numbers from the global CMakeLists if somebody want's to add the LibreOffice wrapper to the cmake build system.~~

Please find the ready built LibreOffice extension and a spreadsheet test file attached for testing (rename both files by removing the .zip extension):

[CoolProp.oxt.zip](https://github.com/CoolProp/CoolProp/files/2716477/CoolProp.oxt.zip)
[TestLibreOffice.ods.zip](https://github.com/CoolProp/CoolProp/files/2716479/TestLibreOffice.ods.zip)

_edit: Added more testing results and updated attached extension file._
_edit: Updated discussion text._
_edit: Updated discussion text and removed WIP status._

### CODE REVIEW

**Comment by spinnau** [comment]
I've made some changes to make the download helper and installer function for the CoolProp Python package also work on macOS. Please find the updated oxt extension file in the PR description above.

**Comment by spinnau** [comment]
I've included the build process for the LibreOffice extension into the global CMakeLists file.

**Comment by spinnau** [comment]
I have made some minor changes (code formatting, copy license file when building the extension) and squashed commits together, that were only bugfixes and small contributions.

**Comment by ibell** [comment]
So is this PR ready to be squash-merged?

**Comment by spinnau** [comment]
From my point of view, it's ready. Anybody else gave it a try?

I don't know if there's anything else necessary regarding release of the LibreOffice extension. It can be built with cmake, but do you normally also automate the upload to sourceforge? I have included a download link in the updated web documentation for the wrapper [here](https://github.com/CoolProp/CoolProp/pull/1773/commits/fbb3a69408f48303926bd549197a1e8921299fd5#diff-7f75e18f1034726518992cc9f92deddbR29), but probably that needs a little more work.

**Comment by ibell** [comment]
Thanks, this is a very nice contribution, merging.  Do you think there are likely to be enough users to make auto-generation of the package worthwhile?

**Pull request merged**
