### PR TITLE
Delphi sample project

### PR DESCRIPTION
**Pull request by bru32**
Creates a ph-chart and identifies some problem areas

### CODE REVIEW

**Comment by jowr** [comment]
That looks good. Thank you Bruce. Would you be so kind and update https://github.com/CoolProp/CoolProp/blob/master/Web/coolprop/wrappers/DelphiLazarus/index.rst as well? Most people look at the homepage and it would be nice if you could add a short text about the new example project there as well to make people aware of its existence.

**Comment by bru32** [comment]
Yes, I will update DelphiLazarus and write some notes. I have been looking through the C interface and will first make sure that the my code does conform.

**Comment by jowr** [comment]
Great, thanks!

**Comment by ibell** [comment]
Can you please update the Delphi docs here: https://github.com/CoolProp/CoolProp/blob/master/Web/coolprop/wrappers/DelphiLazarus/index.rst with regards to the FPU errors?

**Comment by jowr** [comment]
That looks very good already. I think we can merge it to the master branch as soon as the FPU part is included. Thank you for spotting the particular problems related to the Borland compilers in #892, which happens to solve a number of issues for my work as well!

**Comment by jowr** [comment]
@bru32 are you happy with the state of this pull request? Should I have a look at it and merge it if possible?

**Comment by bru32** [comment]
Yes, My Delphi sample is now working fine.  Just before closing down 
last year, I added a grid to the chart.  I'm not really up to speed with 
GitHub so it would be great if you merge it.
Cheers

On 2016/01/07 10:32 AM, Jorrit Wronski wrote:
>
> @bru32 <https://github.com/bru32> are you happy with the state of this 
> pull request? Should I have a look at it and merge it if possible?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CoolProp/CoolProp/pull/893#issuecomment-169596205>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by jowr** [comment]
Thank you for the contribution!

**Pull request merged**
