### PR TITLE
Fix cxx17

### PR DESCRIPTION
**Pull request by ssg-aero**
### Description of the Change
Trim functions are edited according the quoted stackoverflowpost.
[](https://stackoverflow.com/questions/216823/whats-the-best-way-to-trim-stdstring)
### Benefits

Support c++17

### Possible Drawbacks

Needs a c++11 compiler

### CODE REVIEW

**Comment by ibell** [comment]
What is the problem that this PR fixes?

**Comment by ssg-aero** [comment]
Hello,

std::ptr_fun is deprecated since c++11 and removed since c++17 
https://en.cppreference.com/w/cpp/utility/functional/ptr_fun

The post quoted in the modified header propose an alternative using lambda.
https://stackoverflow.com/questions/216823/whats-the-best-way-to-trim-stdstring
The modification simply use this suggestion.

Regards,

Sébastien

**Comment by ibell** [comment]
I'm with you on this, just got bit my this myself.  Does this work in C++11, or is a more recent standard required? If just C++11, I'll merge.

**Comment by ibell** [comment]
Please wrap the code in blocks like this to ensure backwards compatibility with older compilers (for now): https://stackoverflow.com/a/29407260/1360263

Soon we will have to drop old compilers entirely.

**Comment by ssg-aero** [comment]
ok I'll do it and check next year ;)

Happy new year!

**Comment by ssg-aero** [comment]
Legacy support has just been added.

**Comment by ianhbell** [comment]
Thanks, merging!

**Comment by ibell** [comment]
@ssg-aero  Can you please fix this as we discussed in #1995 ?  I got bit by this again.

**Comment by ssg-aero** [comment]
Hi, I've been really busy lately, neither the less I'll try to find a slot to fix it this week.

**Comment by ibell** [comment]
Thank you, would be great

**Comment by ssg-aero** [comment]
Hi, I finally found a slot to work on this and I've just rebased on CoolProp/master and pushed a fix

**Comment by ibell** [comment]
Can you open a new PR?

**Pull request merged**
