### PR TITLE
Update example.py

### LINKED ISSUE #1748: Apostrophe should be escaped in '...' strings or be used in "..." string
https://github.com/CoolProp/CoolProp/blob/5045c963222bff7ecfffaace63487e16b4d43ffe/wrappers/Python/examples/example.py#L87

### PR DESCRIPTION
**Pull request by scls19fr**
Closes #1748

### CODE REVIEW

**Comment by ibell** [comment]
Thanks very much!  Don't know how nobody has noticed this in the last 6 years :(

**Comment by scls19fr** [comment]
Because nobody was using a linter ;-)

**Comment by scls19fr** [comment]
more exactly a code formatter
https://black.readthedocs.io/

```
$ black wrappers/Python/
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/GUI/PsychScript.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/BibtexParser.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/Plots/Plots.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/GUI/CoolPropGUI.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/Plots/PsychScript.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/Plots/PsychChart.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/Plots/ConsistencyPlots.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/Plots/SimpleCyclesCompression.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/Plots/Tests.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/Plots/SimpleCyclesExpansion.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/State.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/__init__.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/tests/runner.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/tests/test_CoolPropState.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/tests/test_Props.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/Plots/Common.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/tests/test_plots.py
error: cannot format /Users/scls/github/scls19fr/CoolProp/wrappers/Python/examples/example.py: Cannot parse: 87:28:     print('************ CAN'T USE REFPROP ************')
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/Plots/psy.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/generate_constants_module.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/pypi/prepare_pypi.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/generate_meta_info.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/CoolProp/Plots/SimpleCycles.py
reformatted /Users/scls/github/scls19fr/CoolProp/wrappers/Python/setup.py
All done! 💥 💔 💥
23 files reformatted, 4 files left unchanged, 1 file failed to reformat.
```

**Comment by ibell** [comment]
Linting welcomed!  Thanks for doing this!

**Pull request merged**
