### PR TITLE
Added Mathcad Wrapper for low-level function set_reference_stateS()

### PR DESCRIPTION
**Pull request by henningjp**
Touched up the README files as well.

### CODE REVIEW

**Comment by ibell** [comment]
Couple of comments:
a) can you please update your branch (see below).  That will resolve all the additional merge comments you see above.
b) There is a conflict in your CMakeLists.txt, please resolve it.
c) How can you be sure that set_reference_state is called before other calls are made?  That is a requirement.  I thought that MathCAD was acausal (therefore indeterminate order of evaluation)?

Generally, it is good practice to:
1) Merge CoolProp:master in your master, make sure they are in sync
2) Make a new branch on your repo for the new feature, modify your code as needed
3) File PR between your branch and CoolProp:master

**Comment by henningjp** [comment]
Ah, Ok.  I was missing the extra branch step.  Want to cancel this one and I'll start over?

I thought I did the merge.  From CoolProp/master, right?
I thought I resolved the conflict as well.  See the last to commits on this chain above marked "Merge remote-tracking branch 'refs/remotes/CoolProp/master'".  What am I doing wrong?

Sorry to be such a Git newb.  I'm getting there, but the nuances are killing me.

**Comment by ibell** [comment]
Yeah git is definitely confusing.  Tools like github and TortoiseGit make life slightly less painful, but from time to time you just get completely stuck with what should be simple problems to resolve.

**Comment by henningjp** [comment]
Not sure if that was a Yes or a no on the PR.  I'll kill it and submit a "better" on on Tuesday evening.

**Comment by ibell** [comment]
It was a "kill it" on this PR.  Hopefully we can get this sorted soonish.  Or we just delay until after v6 release.

**Comment by henningjp** [comment]
I'd really like this one in.  I'll have a new PR, done correctly, tomorrow night.  No worries. Hang on one more day. Thanks.

**Comment by ibell** [comment]
Yup, yup, no problem.

**Comment by ibell** [comment]
I'm still a bit dubious about setting the reference state and
order-of-evaluation...

**Comment by henningjp** [comment]
It works. I have it in my example worksheets, but with warnings (like you have on the web page) to ONLY use it at the beginning of a worksheet and not to flip flop back and forth.  It leads to unexpected results and different results, depending on what was calculated last.  I'll mail you my lastest PDF so you can see how I handle it. It's basically plagerized from the CoolProp web example.

**Pull request closed without merging**
