### PR TITLE
Update setup.py replace distutils with setuptools PEP 632 – Deprecate distutils module

### PR DESCRIPTION
**Pull request by Housebi**
### Description of the Change

Replace all instances of the distutils module with the appropriate setuptools module, or other modules where applicable.

Edit line 4-5:
from distutils.version import LooseVersion
from distutils.sysconfig import get_config_var
To
from packaging.version import Version
from sysconfig import get_config_var

Edit line 291:
cython_version = Version (Cython.__version__)
To
cython_version = str(Version(Cython.__version__))

Edit line 353:
from distutils.errors import CompileError
To
from setuptools import CompileError

Edit line 394:
from Cython.Distutils.extension import Extension
To
from setuptools.extension import Extension

Delete line 396:
from Cython.Distutils import build_ext
This is now handled with line 6 "from setuptools.command.build_ext import build_ext", and thus redundant.

Edit line 3, 60, 61 62, 66, 77, 229, and 291
Replace all instances of LooseVersion with Version

### Benefits

To my understanding, as per PEP 632, the distutils module is being replace with setuptools and as of python 3.12 no longer included.

### Possible Drawbacks

unknown

### Verification Process

Tested by making a new wheel for python 3.13 on Windows 10 64 bit and installed via pip. Tested whether CoolProp could be imported and give simple fluid properties.

### Applicable Issues

Support for python 3.13

### CODE REVIEW

**Comment by Housebi** [comment]
Updated
python-version: 3.12.x to python-version: 3.13.x in python_cibuildwheel.yml and python_buildwheels.yml

Added python 313 to python-version list in python_buildwheels.yml. New list is [38, 39, 310, 311, 312, 313]
python-version: [38, 39, 310, 311, 312, 313]

**Comment by Housebi** [comment]
Looking at the documentation on [cibuildwheel 2.17](https://pypi.org/project/cibuildwheel/2.17.0/), I think we need a newer version for python 3.13. Think would perhaps explain why none of the wheels for python 3.13 are built successfully.

This however still does not explain why none of the windows wheels are built successfully. There appears to be an error that is related to the packaging module. Although it is listed in de dependencies, the error message is, ModuleNotFoundError: No module named 'packaging'.

**Comment by ibell** [comment]
Not sure what happened, but I think something went wrong with the commits, as there are a lot of unrelated files that are now in the commit.

**Comment by Housebi** [comment]
Yes, I noticed, I will compile the changes to setup.py, python_cibuildwheel.yml, and python_buildwheels.yml and start over if I cannot delete the rest.

**Comment by ibell** [comment]
Thanks for taking on the python 3.13 addition!

**Comment by Housebi** [comment]
You are welcome. There is however still one check "testing catch2 / build" that has failed, so perhaps there is still an error somewhere.

**Pull request closed without merging**
