### PR TITLE
CoolPropDbl

### PR DESCRIPTION
**Pull request by mikekaganski**
Introduce CoolPropDbl to replace long doubles. This may help to overcome
possible portability problems, and test for efficiency and precision.

Only C++ files were changed; no .i nor python were changed. I have no idea if this should be done.

### CODE REVIEW

**Comment by ibell** [comment]
I think we need to be fairly careful with this merge.  @jowr, do you know how to merge into a branch rather than into master?

**Comment by mikekaganski** [comment]
Maybe I'll re-request to the branch you need? When I make the request, it gives me opportunity to select the branch, IIRC

**Comment by ibell** [comment]
I want to merge it into another branch so that we can run all the tests on
the branch before we merge into master.  I think it is going to break quite
a lot of things, so I want to be able to see how much gets broken before we
go too far along this path

**Comment by mikekaganski** [comment]
Tell me what branch do you want it to, and I'll re-request it to that branch.

**Comment by ibell** [comment]
I've made you a branch - try this one:
https://github.com/CoolProp/CoolProp/tree/longdouble_remap

**Comment by mikekaganski** [comment]
Done; see #495

**Pull request closed without merging**
