### PR TITLE
LabVIEW VIs to call PropsSI and Props1SI

### PR DESCRIPTION
**Pull request by inamdarharshad**
Please ignore files without their LabVIEW version specified in the filename.

### CODE REVIEW

**Comment by jowr** [comment]
Hey @ibell, should this one be merged?

**Comment by jowr** [comment]
Thanks for the contribution, could you please be more specific? What should be ignored? Can you delete the ignored files from your pull request? Has this been tested? Could you add some documentation to enable others to use your files? The LabView docs can be found here: https://github.com/CoolProp/CoolProp/tree/master/Web/coolprop/wrappers/Labview

**Comment by inamdarharshad** [comment]
I have now obtained access to LabVIEW (I did not have access to LabVIEW in the preceding months. I will go over the files again, add comments to the files, and also make a Word document describing the procedure of using the VIs. I apologize for my tardiness.

**Comment by inamdarharshad** [comment]
[Instructions_for_use_of_CoolProp_VIs_2017-09-24.docx](https://github.com/CoolProp/CoolProp/files/1327070/Instructions_for_use_of_CoolProp_VIs_2017-09-24.docx)
The LabVIEW docs have been revised for the v2009 and v15.0 library and VI submitted to the repository through Pull Requests. I am working on a LabVIEW VI for moist air properties; I hope to be able to create a Pull Request for the VIs soon.

**Pull request closed without merging**
