### PR TITLE
Added details from #820

### PR DESCRIPTION
**Pull request by sabatind**
Now describes manual parameter changes required in CMakeLists.txt, how to change ndk-build options, and how to integrate the generated files into an Android Studio project.

### CODE REVIEW

**Comment by ibell** [comment]
Overall it looks very good and a reasonably savvy person should be able to follow the instructions.

One question: Can you provide a minimal working example of calling into CoolProp from Android?

**Comment by sabatind** [comment]
I did see your comments for my PR.  Sorry for the lack of response.  Based on your suggestion, I created a "hello world" app for CoolProp.  I wasn't sure how to include it in the index.rst file as the other wrappers us literalinclude, so I've included them here for now.  If you point me in the right direction, I'd be happy to add them to the index.rst file.  At the same time I'm glad to fix the formatting on that file (the lines with hashtags don't recognize the carriage return), just haven't figured out what I am doing wrong.

***mainactivity.java***
```java
package com.example.coolprop.androidexample;

import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.TextView;


public class MainActivity extends ActionBarActivity {

    static {
        System.loadLibrary("CoolProp");
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        TextView CoolPropsDisplay = (TextView) findViewById(R.id.CoolPropsDisplay);
        CoolPropsDisplay.setText(Double.toString(CoolProp.PropsSI("T", "P", 101300, "Q", 0, "Water")));
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}
```

***activity_main.xml***
```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent"
    android:layout_height="match_parent" android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:paddingBottom="@dimen/activity_vertical_margin" tools:context=".MainActivity">

    <LinearLayout
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:orientation="vertical">

        <TextView
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:textSize="40dp"
            android:gravity="center"
            android:id="@+id/CoolPropsDisplay"
            android:layout_weight="1"
            android:textAlignment="gravity" />

    </LinearLayout>

</RelativeLayout>
```

**Comment by ibell** [comment]
To add them to index.rst, you need to end the preceding line with ::, add an empty line, and then indent the code block by 4 characters.  That's it.  I can tidy up afterwards if need be.  You've done the hard work.

**Comment by sabatind** [comment]
A few quick attempts and I didn't get it to work.  A bit too busy to do a proper job.  I'll have more time in a few days to do get it right.

**Comment by sabatind** [comment]
My apologies for my lack of progress on this.  Pressing matters kept me away far longer than I had expected.  However, I finally returned to this task and after a little reST markup primer I got example code inserted into the .rst file along with some formatting improvements.  I  committed the updates to the push request.  Please let me know if that will work.  Once again, sorry for the delay.

**Comment by ibell** [comment]
All looks great to me.  Thanks for your work on this!

**Pull request merged**
