### PR TITLE
Update Mathcad docs for pre-compiled and discontinuation of Legacy Mathcad [skip-ci]

### PR DESCRIPTION
**Pull request by henningjp**
### Description of the Change

Docs update to take into account 
- current state of Mathcad (deprecation of Legacy Mathcad and Mathcad Prime 1-6), and 
- updates to README and Web files
- restructured directories, promoting Mathcad Prime installation using pre-compiled binaries
- left Legacy Mathcad files in subdirectory in case someone has a perpetual license and wants to build their own DLL

### Benefits

No code changes.
Updates will assist users in installation of pre-compiled binaries from SourceForge.
Reflects current state of the Mathcad Prime product from PTC and deprecation of older legacy versions.

### Possible Drawbacks

Had to move a couple of binaries.  Didn't update them but restructuring the directories may be undesirable from a GitHub storage space perspective.  Last time since Legacy Mathcad (15) is now fully deprecated.

### Verification Process

Viewed README files on fork for proper rendering.

### Applicable Issues

Precompiled binaries re-instated on SourceForge (manually for now).  Cloases #1944

### CODE REVIEW

**Comment by henningjp** [comment]
@ibell - Can be **squash merged**, but I wanted to make you aware that I had to move two binaries in the directory structure.   This probably, in effect, removed two and added two.  Should be the last time since Legacy Mathcad is fully deprecated.  No way around it since the example files are binary.

**Comment by henningjp** [comment]
Don't merge yet.  I just found another typo on the web page that I have to fix.

**Comment by henningjp** [comment]
It’s ok to squash merge now.  No typo.

**Comment by ibell** [comment]
Cool, squash-merging

**Pull request merged**
