### PR TITLE
IF97 Backend: Additional Input Pairs and Transport Properties

### PR DESCRIPTION
**Pull request by henningjp**
- [x] Input pairs for ``(p,h)``, ``(p,s)``, and ``(h,s)`` implemented in IF97 Backend
- [x] Transport  properties implemented in IF97 Backend

Closes Issue #1249 (tested)

### CODE REVIEW

**Comment by henningjp** [comment]
Verification documents (through Mathcad interface) attached here:
[Backward Test.pdf](https://github.com/CoolProp/CoolProp/files/721228/Backward.Test.pdf)
[Transport Test.pdf](https://github.com/CoolProp/CoolProp/files/721229/Transport.Test.pdf)

**Comment by ibell** [comment]
Merged outstanding PR, can you please update this PR?

**Comment by henningjp** [comment]
Sorry, I don't understand.  Git says "Everything is up-to-date".  Update this PR how?

**Comment by henningjp** [comment]
Updated text of PR.

**Pull request merged**
