### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by jfCoronel**
- Updating the PropiedadesDeFluidos link
- Adding a new app 'CuadernoDeProblemas' that uses CoolProp

### Requirements

* Fill out this template to the extent possible so that this PR can be reviewed in a timely manner.
* Replace the bracketed text below with your own.
* All new code requires tests to ensure against regressions.

### Description of the Change

[ Updating index.rst:
- Updating the PropiedadesDeFluidos link
- Adding a new app 'CuadernoDeProblemas' that uses CoolProp ]

### Benefits

[Correct links ]

### Possible Drawbacks

[ None]

### Verification Process

[  new links URL verified ]

### Applicable Issues

[ ]

### CODE REVIEW

**Comment by ibell** [comment]
Can you please add a few words in your link about what this is for those that are English-only?

**Comment by jfCoronel** [comment]
> 

Changed Links, short English description added using the flags buttons

**Comment by ibell** [comment]
I don't think that worked, I still only see the Spanish

**Comment by jfCoronel** [comment]
> I don't think that worked, I still only see the Spanish
> […](#)
> Message ID: ***@***.***>

It Changes to English by clicking in the flag

Captura de pantalla 2023-04-19 a las 14 13 48

Captura de pantalla 2023-04-19 a las 14 13 28

**Comment by jfCoronel** [comment]
> Ah, but the changes were not made in index rst, that's what I had in mind. It would be nice at least to have also an English translation.

ok, English translation of the app names added.

**Comment by ibell** [comment]
Thank you

**Pull request merged**
