### PR TITLE
CoolPropDbl

### PR DESCRIPTION
**Pull request by mikekaganski**
Introduce CoolPropDbl to replace long doubles. This may help to overcome
possible portability problems, and test for efficiency and precision.

### CODE REVIEW

**Comment by ibell** [comment]
Ok, let's see how the testing looks.  I'm quite curious.  And then we can add a preprocessor macro that allows you to disable the mapping

**Comment by mikekaganski** [comment]
Unfortunately, I cannot test it (I mean both performance and precision) - I only have MS VC++ under Win7x64, and there long double == double.

**Comment by ibell** [comment]
Right, thats where our buildbot network is useful:
http://www.coolprop.dreamhosters.com:8010/

**Comment by ibell** [comment]
I just fired off all the builders on that branch, let's see what the
results are - you can see it in the grid

**Pull request merged**
