### PR TITLE
Add Rust Wrapper

### PR DESCRIPTION
**Pull request by sgolle**
Signed-off-by: Steffen Golle <somnium@stampernet.de>

### Requirements

- Working clang installation
- Working CoolProp installation with shared library and header files in system path
- Working Rust environment

### Description of the Change

- First experimental implementation of a Rust wrapper

### Benefits

- Use CoolProp in Rust

### Possible Drawbacks

- Possible bugs in the bindings to C++ code

### Verification Process

- Unit tests of the high level implementation functions props_si() and ha_props_si()

### Applicable Issues

Rust Wrapper #1605

### CODE REVIEW

**Comment by ibell** [comment]
Can you please use the same function names as in CoolProp unless this is banned by rust?

**Comment by sgolle** [comment]
The rust naming convention wants no camel cases, that's why I changed it. But I can change it, so that it fits CoolProp. I do also think that wrappers/Rust should be linked to the associated repository (coolprop-rs) as a submodule, so that bugfixes etc. can be implemented separately from new pull requests.

**Comment by ibell** [comment]
Can you please not put your own repo as a submodule? That can cause troubles down the road, and if you _are_ going to go for an external, please make a new repo within the CoolProp project so that the likelihood of it still existing in 20 years is higher.

**Comment by sgolle** [comment]
I removed the submodule and add version 0.2.0 of the rust wrapper.

**Comment by ibell** [comment]
Thanks, are we ready to merge this?

**Comment by sgolle** [comment]
Everything looks good. From my side it can be merged.

**Comment by ibell** [comment]
Do you want to add a bit of information to the docs too: https://github.com/CoolProp/CoolProp/tree/master/Web/coolprop/wrappers

**Pull request merged**
