### PR TITLE
Add error handling to Julia's wrapper

### PR DESCRIPTION
**Pull request by JonWel**
Add error handling to Julia's wrapper (works for Julia 0.4, still not working with Julia's 0.3 Ubuntu ppa).

Changed numeric input requirement to be ´Number´ instead of restricting to ´Float64´, that allows both integer and floats to be used as input with few overhead (the Float64 version is still internally created by Julia and the overhead for the conversion from Int64 to Float64 seems negligible compare to the execution time from the functions, I could only time a difference in jit compilation time).
Added ´K2F´,  ´get_global_param_string´ and ´get_param_index´ functions
Also add usage of Props1SI when two string arguments are given to PropsSI.

(I see that my update from the CoolProp GitHub to my cloned repository is put in the list of commits, if someone has advice for better practices to send only the needed commits, It's welcome).

### CODE REVIEW

**Comment by ibell** [comment]
Are you interested in also wrapping the low-level interface functions as well that can be used to handle the AbstractState handle from high-level languages without needing native-language support?  These would be the AbstractState_factory, _free, etc. : https://github.com/CoolProp/CoolProp/blob/master/include/CoolPropLib.h#L231

I'm going to merge this now though.

**Comment by JonWel** [comment]
I'm interested, but I will need some time to understand a bit better the way it works.
I'm new to C++ (pointers, objects, ...) and as I understand by now the AbstractState should be used as an object.
Julia has a way to deal with objects, but differently from what I remember from python.

**Comment by JonWel** [comment]
Until now, implementing access in the form of Julia functions seems to work (at least it do not segfault):

    # EXPORT_CODE long CONVENTION AbstractState_factory(const char* backend, const char* fluids, long *errcode, char *message_buffer, const long buffer_length);
    function AbstractState_factory(backend::String, fluids::String)
      message_buffer = Array(UInt8, 255)
      errcode = 0
      AbstractState = ccall( (:AbstractState_factory, "CoolProp"), Clong, (Ptr{UInt8},Ptr{UInt8},Ref{Clong},Ptr{UInt8},Clong), backend,fluids,errcode,message_buffer,length(message_buffer))
      if errcode != 0
        error("CoolProp:", bytestring(convert(Ptr{UInt8}, pointer(message_buffer))))
      end
      return AbstractState
    end

    # EXPORT_CODE void CONVENTION AbstractState_free(const long handle, long *errcode, char *message_buffer, const long buffer_length);
    function AbstractState_free(handle::Clong)
      message_buffer = Array(UInt8, 255)
      errcode = 0
      ccall( (:AbstractState_free, "CoolProp"), Void, (Clong,Ref{Clong},Ptr{UInt8},Clong), handle,errcode,message_buffer,length(message_buffer))
      if errcode != 0
        error("CoolProp:", bytestring(convert(Ptr{UInt8}, pointer(message_buffer))))
      end
      return nothing
    end

Is it possible to have some numeric values corresponding to ´CoolProp.PT_INPUTS´ and some keyed outputs to test more easily the functions?
(I'll also try to implements Julia functions to give theses numerical values).

Once the Julia Functions will be working, I'll look what I can do to make it more similar from python in the usage ([objects in Julia](https://thenewphalls.wordpress.com/2014/02/19/understanding-object-oriented-programming-in-julia-part-1/)

**Comment by JonWel** [comment]
This was easier than I expected:

    julia> import CoolProp

    julia> handle = CoolProp.AbstractState_factory("HEOS", "Water")
    0

    julia> PT_INPUTS = CoolProp.get_input_pair_index("PT_INPUTS")
    7

    julia> cpmass = CoolProp.get_param_index("C")
    34

    julia> CoolProp.AbstractState_update(handle,PT_INPUTS,101325, 300)

    julia> CoolProp.AbstractState_keyed_output(handle,cpmass)
    4180.635776569655

    julia> CoolProp.AbstractState_free(handle)

    julia> 

So access to the functions from the low level interface works.

I think it's already a good step in the direction to the integration of the low level interface, I'll do a pull request with it.

**Comment by ibell** [comment]
Exactly!  Can you also add this as an example to the low-level-interface
page in the docs?

**Comment by JonWel** [comment]
Here http://www.coolprop.org/coolprop/LowLevelAPI.html ?

Or in the Julia wrapper's doc: http://www.coolprop.org/coolprop/wrappers/Julia/index.html#usage ?

**Comment by ibell** [comment]
I think in the low-level docs, as a demonstration of how to use the
low-level wrapper from languages that don't do classes

**Comment by JonWel** [comment]
Ok.
While furthermore checking my wrapper, I found that the handling the ´errcode´ variable is not done correctly (always 0 value, even when errors occurs).

I have to check how to correctly pass the pointer to this variable and correct this.

**Comment by JonWel** [comment]
My code creates the ´message_buffer = Array(UInt8, 255)´ for each function.
When that was only done when raising an error, that was not bad, but now that it is to run the low level interface, I think it is way suboptimal.

I will define a global string buffer and errcode that will be created only once when the module is loaded and used by all functions.
I think this will be better in term of performances.

**Comment by JonWel** [comment]
There is three different error code returned to the ´errcode´ variable:
0 => no error
1 => error sent to the error buffer => I send the message from the buffer
2 => buffer too small => I send a message saying that the buffer is too small
3 => ? (it do not appears in all low level functions, it is the catch(...), that takes all other exceptions that catch(std::exception &e) don't).

I think that is is better that I use theses numbers to adapt the error message send, but I'm unsure for the third message. "Unknown error" ?

**Comment by ibell** [comment]
Yes it looks like where there is an ValueError error (in the catch(...) branch), the error message doesn't get copied.  That's not good.  See #535.  I plan to fix that tonight.

**Comment by ibell** [comment]
The error message should be in the buffer if the error message buffer is
big enough.  Otherwise there will be an error message code that is not zero

**Comment by 11718pauld** [comment]
```julia
using PyCall
@pyimport CoolProp.constants as CPc
@pyimport CoolProp.CoolProp as CP
import CoolProp
```
```julia
len = 2500
p = 1e6*linspace(2.8,3,len)
h = 1e3*linspace(700,1500,len)

#Abstract Class via pycall
tic()
for i = 1:len
st = CP.AbstractState("HEOS","water")
(pair, in1, in2) = CP.generate_update_pair(CPc.iP,p[i], CPc.iHmass, h[i])
st[:update](pair, in1, in2)
st[:keyed_output](CPc.iDmass)
end
toc()

#Direct PyCall
tic()
for i = 1:len
CP.PropsSI("D","P",p[i],"H",h[i],"Water")
end
toc()

#CoolProp Wrapper
tic()
for i = 1:len
CoolProp.PropsSI("D","P",p[i],"H",h[i],"Water")
end
toc()

#Abstract Class Coolprop(nightly_builds)
handle = CoolProp.AbstractState_factory("HEOS", "Water")
tic()
for i = 1:len
CoolProp.AbstractState_update(handle,CoolProp.get_input_pair_index("HmassP_INPUTS"),p[i],h[i])
CoolProp.AbstractState_keyed_output(handle,CoolProp.get_param_index("D"))
end
toc()
CoolProp.AbstractState_free(handle)
```

Output:
```
elapsed time: 2.63039764 seconds
elapsed time: 1.85618946 seconds
elapsed time: 1.999299566 seconds
elapsed time: 1.507889321 seconds
```

**Comment by JonWel** [comment]
I can reproduce theses results (with Julia 0.3).

It seems there is a performance regression between the nightly build and the 5.0.8 release (PropsSI is faster in 5.0.8 than in the nightly), this explain why python run faster (Python run the 5.0.8 release).

**Comment by jowr** [comment]
You should not create a new state object inside the loop. Could you update your example and remove `st = CP.AbstractState("HEOS","water")` from the loop? This is only needed once.

**Comment by JonWel** [comment]
With Julia 0.3.6-depsfix9-utopic ppa:

    using PyCall
    @pyimport CoolProp.constants as CPc
    @pyimport CoolProp.CoolProp as CPpy
    import CoolProp


    len = 2500
    p = 1e6*linspace(2.8,3,len)
    h = 1e3*linspace(700,1500,len)

    #Abstract Class via pycall
    function PyAC(p,h)
      st = CPpy.AbstractState("HEOS","water")
      for i = 1:len
        (pair, in1, in2) = CPpy.generate_update_pair(CPc.iP,p[i], CPc.iHmass, h[i])
        st[:update](pair, in1, in2)
        st[:keyed_output](CPc.iDmass)
      end
    end

    #Direct PyCall
    function PyDir(p,h)
      for i = 1:len
        CPpy.PropsSI("D","P",p[i],"H",h[i],"Water")
      end
    end

    #CoolProp Wrapper
    function dir(p,h)
      for i = 1:len
        CoolProp.PropsSI("D","P",p[i],"H",h[i],"Water")
      end
    end

    #Abstract Class Coolprop
    function AC(p,h)
      handle = CoolProp.AbstractState_factory("HEOS", "Water")
      HmassP_INPUTS = CoolProp.get_input_pair_index("HmassP_INPUTS")
      D = CoolProp.get_param_index("D")
      for i = 1:len
        CoolProp.AbstractState_update(handle,HmassP_INPUTS,p[i],h[i])
        CoolProp.AbstractState_keyed_output(handle,D)
      end
      CoolProp.AbstractState_free(handle)
    end


    println("Python PropsSI: ")
    @time PyDir(p,h)
    gc()
    println("Python Abstract Class: ")
    @time PyAC(p,h)
    gc()
    println("PropSI: ")
    @time dir(p,h)
    gc()
    println("Abstract Class: ")
    @time AC(p,h)
    gc()

Results:

    Python PropsSI: 
    elapsed time: 2.185456985 seconds (3123768 bytes allocated)
    Python Abstract Class: 
    elapsed time: 2.56537773 seconds (16004312 bytes allocated)
    PropSI: 
    elapsed time: 2.473641239 seconds (263768 bytes allocated)
    Abstract Class: 
    elapsed time: 1.769120681 seconds (383832 bytes allocated)

**Comment by 11718pauld** [comment]
```julia
len = 2500
p = 1e6*linspace(2.8,3,len)
h = 1e3*linspace(700,1500,len)

#Abstract Class via pycall
tic()
for i = 1:len
st = CP.AbstractState("HEOS","water")
(pair, in1, in2) = CP.generate_update_pair(CPc.iP,p[i], CPc.iHmass, h[i])
st[:update](pair, in1, in2)
st[:keyed_output](CPc.iDmass)
end
toc()

#Direct PyCall
tic()
for i = 1:len
CP.PropsSI("D","P",p[i],"H",h[i],"Water")
end
toc()

#CoolProp Wrapper
tic()
for i = 1:len
CoolProp.PropsSI("D","P",p[i],"H",h[i],"Water")
end
toc()

#Abstract Class Coolprop(nightly_builds)
handle = CoolProp.AbstractState_factory("HEOS", "Water")
D = CoolProp.get_param_index("D")
HmassP_INPUTS = CoolProp.get_input_pair_index("HmassP_INPUTS")
tic()
for i = 1:len
CoolProp.AbstractState_update(handle,HmassP_INPUTS,p[i],h[i])
CoolProp.AbstractState_keyed_output(handle,D)
end
toc()
CoolProp.AbstractState_free(handle)
```
Output:
```julia
elapsed time: 2.83010061 seconds
elapsed time: 1.883818782 seconds
elapsed time: 2.033662344 seconds
elapsed time: 1.511830794 seconds
```
Removing the objects from the loop, not much of a diff !. Is the approach correct?
I need go for the Tabular approach, for speed.

**Comment by JonWel** [comment]
@11718pauld you removed the abstract creation line on the Julia side, but not on Python's.
´st = CP.AbstractState("HEOS","water")´ is still in the loop.

**Comment by 11718pauld** [comment]
..oops...
```julia
len = 2500
p = 1e6*linspace(2.8,3,len)
h = 1e3*linspace(700,1500,len)

#Abstract Class via pycall
tic()
st = CP.AbstractState("HEOS","water")
for i = 1:len
(pair, in1, in2) = CP.generate_update_pair(CPc.iP,p[i], CPc.iHmass, h[i])
st[:update](pair, in1, in2)
st[:keyed_output](CPc.iDmass)
end
toc()

#Direct PyCall
tic()
for i = 1:len
CP.PropsSI("D","P",p[i],"H",h[i],"Water")
end
toc()

#CoolProp Wrapper
tic()
for i = 1:len
CoolProp.PropsSI("D","P",p[i],"H",h[i],"Water")
end
toc()

#Abstract Class Coolprop(nightly_builds)
handle = CoolProp.AbstractState_factory("HEOS", "Water")
D = CoolProp.get_param_index("D")
HmassP_INPUTS = CoolProp.get_input_pair_index("HmassP_INPUTS")
tic()
for i = 1:len
CoolProp.AbstractState_update(handle,HmassP_INPUTS,p[i],h[i])
CoolProp.AbstractState_keyed_output(handle,D)
end
toc()
CoolProp.AbstractState_free(handle)
```
Output
```julia
elapsed time: 2.574164707 seconds
elapsed time: 1.936715418 seconds
elapsed time: 2.010144981 seconds
elapsed time: 1.519889089 seconds
```
I was just expecting abstract class to be much much faster than using propsSI.
Nevertheless, I shall go for Tabular methods for simulation ~

**Comment by 11718pauld** [comment]
@JonWel ...Any suggestion for wrapping up the Tabular Method in Julia?
This can shoot the speed tremendously !

**Comment by jowr** [comment]
What is wrong with `handle = CoolProp.AbstractState_factory("TTSE", "Water")`?

**Comment by 11718pauld** [comment]
@jowr ...Didn't have the idea indeed !!!

**Comment by 11718pauld** [comment]
Is it available in the current nightly-build shared library?
I am getting an error with with TTSE&HEOS
```
"TTSE&XXXX": The TTSE backend will be used, and the tables will be generated using the XXXX backend where XXXX is one of the base backends("HEOS", "REFPROP", etc. )
"BICUBIC&XXXX": The Bicubic backend will be used, and the tables will be generated using the XXXX backend where XXXX is one of the base backends("HEOS", "REFPROP", etc. )
```

**Comment by JonWel** [comment]
Here is what I get when I try the TTSE:
``` julia
julia> import CoolProp

julia> handle = CoolProp.AbstractState_factory("TTSE&HEOS", "Water")
Loading table: /home/johndoe/.CoolProp/Tables/HelmholtzEOSBackend(Water)/single_phase_logph.bin.z
Loaded table: /home/johndoe/.CoolProp/Tables/HelmholtzEOSBackend(Water)/single_phase_logph.bin.z in 0.097623 sec.
Loading table: /home/johndoe/.CoolProp/Tables/HelmholtzEOSBackend(Water)/single_phase_logpT.bin.z
Loaded table: /home/johndoe/.CoolProp/Tables/HelmholtzEOSBackend(Water)/single_phase_logpT.bin.z in 0.1072 sec.
Loading table: /home/johndoe/.CoolProp/Tables/HelmholtzEOSBackend(Water)/pure_saturation.bin.z
Loaded table: /home/johndoe/.CoolProp/Tables/HelmholtzEOSBackend(Water)/pure_saturation.bin.z in 0.001162 sec.
0

julia> CoolProp.AbstractState_update(handle,7,101325, 300) # PT_INPUTS

julia> CoolProp.AbstractState_keyed_output(handle,34)
ERROR: CoolProp: Error: calc_cpmolar is not implemented for this backend
 in AbstractState_keyed_output at /home/johndoe/.julia/v0.3/CoolProp/src/CoolProp.jl:155

julia> CoolProp.AbstractState_keyed_output(handle,33)
ERROR: CoolProp: Error: calc_molar_mass is not implemented for this backend
 in AbstractState_keyed_output at /home/johndoe/.julia/v0.3/CoolProp/src/CoolProp.jl:155

julia> CoolProp.AbstractState_keyed_output(handle,32)
ERROR: CoolProp: Error: calc_molar_mass is not implemented for this backend
 in AbstractState_keyed_output at /home/johndoe/.julia/v0.3/CoolProp/src/CoolProp.jl:155

julia> CoolProp.AbstractState_keyed_output(handle,31)
ERROR: CoolProp: Error: calc_molar_mass is not implemented for this backend
 in AbstractState_keyed_output at /home/johndoe/.julia/v0.3/CoolProp/src/CoolProp.jl:155
```

I never had used the tables, so I do not know how I should use them.

**Comment by jowr** [comment]
It's probably not your fault. @ibell has worked a lot on the tables recently, but I don't think it's ready yet... I might be able to give a hand in April or May, but not now.

**Comment by 11718pauld** [comment]
@jowr ...no problem. I can wait, and can try the Wrappers/benchmarks when ready.....

**Comment by ibell** [comment]
@11718pauld , please don't add comments to closed PR or issues, it makes it very hard to track what things need to be fixed.  Please open new issues.  

That said, the tables are a work in progress.  You'll see there are a handful of open issues having to do with Bicubic or TTSE interpolation.  Cp (neither mass nor molar) are implemented because they are derivatives, and I just haven't done that yet.  Molar mass is a similar story (that is a 5 second fix).  The examples shown on the Tabular interpolation page of the docs should work: http://www.coolprop.dreamhosters.com:8010/binaries/sphinx/coolprop/Tabular.html

**Pull request merged**
