### PR TITLE
Update build process for LibreOffice wrapper

### PR DESCRIPTION
**Pull request by spinnau**
### Description of the Change

Since LibreOffice SDK 7.4 the UNOIDL compiler `idlc` is deprecated and replaced by `unoidl-write`. In SDK versions >= 7.5 the old compiler is removed. Extensions created with the new compiler will also run on older LibreOffice versions. This PR updates the build process for the LibreOffice CoolProp extension:

- Using new `unoidl-write` compiler to build the extension
- Adapt UNO IDL API changes for identifiers
- Enable install of CoolProp Python package development versions inside the LibreOffice extension
- Add a GitHub workflow to build the LibreOffice wrapper

### Benefits

* Allow building the extension with new LibreOffice SDK versions
* Automation of the build process for releases

### Verification Process

* The build workflow on GitHub was successfully tested: https://github.com/spinnau/CoolProp/actions/runs/7409603133

* The LibreOffice extension built has been tested and works as expected on:
   - LibreOffice 7.3.5.2 (Win 10)
   - LibreOffice 7.6.4.1 (Win 10)
   - LibreOffice 7.6.4.1 (Linux)

### CODE REVIEW

**Comment by spinnau** [comment]
It would also make sense to include the LibreOffice builder workflow in the `Release workflow run` action.

**Comment by ibell** [comment]
Is this ready for merge?

**Comment by spinnau** [comment]
From my point of view, it's ready. Before merging, I could also add a commit to include the LibreOffice builder to the release workflow in https://github.com/CoolProp/CoolProp/blob/master/.github/workflows/release_all_files.yml#L73.

**Comment by ibell** [comment]
So, ready now?

**Comment by spinnau** [comment]
Yes, it can be merged now.

**Pull request merged**
