### PR TITLE
Fluids alias additions

### PR DESCRIPTION
**Pull request by wandadars**
### Requirements

* Fill out this template to the extent possible so that this PR can be reviewed in a timely manner.
* Replace the bracketed text below with your own.
* All new code requires tests to ensure against regressions.

### Description of the Change

[ Added aliases for the following fluid species 

m-Xylene.json	
n-Butane.json	
n-Decane.json	
n-Dodecane.json	
n-Heptane.json	
n-Hexane.json	
n-Nonane.json	
n-Octane.json
n-Pentane.json	
n-Propane.json	
n-Undecane.json	
o-Xylene.json	
p-Xylene.json	
]

### Benefits

[ More aliases for access fluid property data ]

### Possible Drawbacks

[ Fluids with overlapping aliases(no overlaps for the aliases that I added) ]

### Verification Process

[ I was hoping that there was a CI tester for PRs. I performed the edits within GitHub.

### Applicable Issues

[ None ]

### CODE REVIEW

**Comment by thorade** [comment]
As discussed here:
https://groups.google.com/forum/#!topic/coolprop-users/KJ8xbcGFonU
Looks good to me

**Comment by ibell** [comment]
Since you seem to be pretty up on your git-fu, do you have any interest in fixing the INChI keys?  I put in the non-standard INChI keys (oops), and it would be better to have the standard INChI keys and INChI strings.

**Comment by ibell** [comment]
Also, thank you very much for this PR

**Comment by wandadars** [comment]
Did you put some standard keys in there? I compared the InChi key & string in the database to what the winchi-1 software produces, and the values were the same. The strings & keys listed in winchi-1 don't have any markers that say whether they are standard or non-standard, so that isn't helping my confusion haha.

**Comment by wandadars** [comment]
@ibell The PR for the InChi keys and strings is completed.

**Comment by ibell** [comment]
You're amazing! Thanks so much for doing this!

**Pull request merged**
