### PR TITLE
Primitive structures simplification attempt 2

### PR DESCRIPTION
**Pull request by mikekaganski**
This time I tested everything under Ubuntu.

-> I reworked primitive structures simplification. This time I don't use c++11 syntax
```c++
var = struct{init_list}
```
Instead, good old structure initializer
```c++
var = {init_list}
```
is used. I'm doing this to allow compiler to compile these primitive structures into library as blobs, ready to use without initialization. They are anyway only needed to initialize smart classes. Now it looks like this:
- strings and numbers are stored in the library binary (data section) and loaded into the memory on library load
- this data is used to initialize array of structs (using a number of calls to struct contructor, and to std::string constructors inside)
- this array is used to initialize static info class object (through its constructor).

I hope to do this:
- array with strings and numbers is stored in library binary and loaded into memory
- this array is used to initialize static info class object

-> Removed <memory> include that I added to use std::shared_ptr (reverted by b28583f4b6e2e861b75a0293c07d9bf9bc0e4005).

-> Fixed compiler warning that deleting void* is undefined

Further commits will be tested under Linux, too. Hope that I will not create much troubles anymore. Sorry for being ignorant.

### CODE REVIEW

**Comment by ibell** [comment]
And this should compile with C++03?

**Comment by mikekaganski** [comment]
yes, I believe so

**Comment by ibell** [comment]
Right, well lets see how it goes when I merge.  Are you getting error messages when builds fail on buildbot?  You should be I think...

**Comment by mikekaganski** [comment]
> You should be I think
No I'm not. Should I?

**Pull request merged**
