### PR TITLE
Update PureFluids.py

### PR DESCRIPTION
**Pull request by whunter7**
@jowr Correct specific_heat and conductivity data for Syltherm 800

### CODE REVIEW

**Comment by jowr** [comment]
This looks good to me, but I did not check the temperatures. You did extract the data at the same temperatures (-40 to +398 degrees Celsius), right?

**Comment by whunter7** [comment]
That's right. I've checked the other values. Only conductivity and heat capacity were incorrect. I've attached the csv file I downloaded from Dow's online FLUIDFILE software.
[syltherm_fluidfile.txt](https://github.com/CoolProp/CoolProp/files/1001247/syltherm_fluidfile.txt)

**Comment by jowr** [comment]
Thanks for one more fix! Is there more to come or should I merge the changes?

**Comment by whunter7** [comment]
Please merge for now. I plan to add more incompressible fluids later. I'll
submit another pull request when I'm more familiar with CoolProp.

**Pull request merged**
