### PR TITLE
Move F2K into emscripten_interface.cxx

### PR DESCRIPTION
**Pull request by ianhbell**

### CODE REVIEW

**Comment by jowr** [comment]
I thikn this broke the wrapper didn't it?

**Comment by ibell** [comment]
I did, yes, but I fixed it in b59dc.

**Comment by jowr** [comment]
No worries, b59dc8dbe1fd41d7880d3256fcae5ac62af3f4b8 is one of my commits and that is also the one that fixed it 😉

**Comment by ianhbell** [comment]
That’s what I get for not testing my commit ☺

**Pull request merged**
