### PR TITLE
Misc. typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -i 3 -w -I ../coolprop-word-whitelist.txt` whereby whitelist consists of:  
```
cas
formate
hel
nd
te
tim
ue
uint
```

### CODE REVIEW

**Comment by ibell** [comment]
Wow.  This is amazing.  I'm amazed (and saddened) that we had so many typos.  Just glad they are fixed now.

**Comment by thorade** [comment]
Nice, I did not know about codespell, but I have used this tool in the past:
https://github.com/vlajos/misspell-fixer
Will also run that and see if it finds anything

**Comment by henningjp** [comment]
Ha!  I was wondering why that @suppress command wasn’t working in mixtures.rst.  Didn’t realize I had misspelled it!  I was blaming it on Sphinx.  Mystery solved.  I’ll check the dev docs and make sure it’s behaving as intended and makes sense.

**Comment by henningjp** [comment]
Hmmm.  @suppress still doesn’t suppress the output, even when it’s spelled correctly.  Maybe the dev docs haven’t been built yet with this merge?

**Pull request merged**
