### PR TITLE
Export first_partial_deriv, see #946

### PR DESCRIPTION
**Pull request by JonWel**
The file `CoolPropLib.def` has not been updated in in this patch.

### CODE REVIEW

**Comment by ibell** [comment]
Can you update the .def too please?

**Comment by JonWel** [comment]
I've never did that (the .def), how should I find the correct number after the @ ?

```c++
AbstractState_first_partial_deriv = _AbstractState_first_partial_deriv@??
```

**Comment by ibell** [comment]
When you build the dll with msvc I thought we wrote the exported symbols to
a exports.txt with dumpbin

**Comment by JonWel** [comment]
Ok, so I hove to compile on Windows.
(I did only checked on Linux)

**Comment by ibell** [comment]
Don't worry then, I'll fix that, thanks for the code...

**Comment by JonWel** [comment]
This is also good for me to know:
```C++
AbstractState_first_partial_deriv = _AbstractState_first_partial_deriv@28
```
Should be the correct one, I add it to the patch and make a new pull request.

**Pull request closed without merging**
