### PR TITLE
[msgpack] update dependency

### LINKED ISSUE #1586: Update msgpack
Would you mind updating msgpack to a more recent version? I ran into compilation errors when attempting to build with a newer version.

### PR DESCRIPTION
**Pull request by xoviat**
Closes #1586.

### CODE REVIEW

**Comment by jowr** [comment]
Thank you for the PR, I haven't checked the msgpack code, but I assume that it was necessary to pass objects/references instead of pointers?

**Comment by ibell** [comment]
Is this PR complete?

**Comment by xoviat** [comment]
Yes.

> but I assume that it was necessary to pass objects/references instead of pointers

They changed it to a `const&`.

**Comment by ibell** [comment]
That's actually a pretty good idea on their part.  Merging...

**Pull request merged**
