### PR TITLE
Improve Robustness of IF97 Reverse (P,H) and (P,S) Evaluations Along Saturation Curve 

### LINKED ISSUE #1918: Bug in IF97 back end
Hi,

I randomly found a bug in the IF97 back end for calculation from HmassP_INPUTS at the saturated liquid state using the following inputs:

``` python
import CoolProp as CP

state = CP.AbstractState(back_end, 'water')

h = 146644.8016353955
p = 5628.620143029655
state.update(CP.HmassP_INPUTS, h, p)
state.smass() --> 505.16763080883464
h = 146644.8016353955
p = 5628.621143029655
state.update(CP.HmassP_INPUTS, h, p)
state.smass() --> 8351.93742026566
```

The bug does not appear in the HEOS back end:

``` python
import CoolProp as CP
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

for back_end in ['HEOS', 'IF97']:

    state = CP.AbstractState(back_end, 'water')

    h = 146644.8016353955
    p = 5628.620143029655
    state.update(CP.HmassP_INPUTS, h, p)
    print(state.smass())
    p = 5628.621143029655
    state.update(CP.HmassP_INPUTS, h, p)
    print(state.smass())

    p_min = 5600
    p_max = 5700

    p_range = np.geomspace(p_min, p_max, 1e3)

    df = pd.DataFrame(columns=['s', 'T', 'rho'])

    for p in p_range:
        try:
            state.update(CP.HmassP_INPUTS, h, p)
            df.loc[p, 's'] = state.smass()
            df.loc[p, 'T'] = state.T()
            df.loc[p, 'rho'] = state.rhomass()
        except ValueError:
            df.loc[p, 's'] = np.nan
            df.loc[p, 'T'] = np.nan
            df.loc[p, 'rho'] = np.nan

    fig, ax = plt.subplots(3, 1)

    ax[0].scatter(df.index, df['s'], marker='x')
    ax[0].grid()
    ax[0].set_xlabel('pressure in Pa')
    ax[0].set_ylabel('entropy in J/kgK')
    ax[1].scatter(df.index, df['T'], marker='x')
    ax[1].grid()
    ax[1].set_xlabel('pressure in Pa')
    ax[1].set_ylabel('temperature in K')
    ax[2].scatter(df.index, df['rho'], marker='x')
    ax[2].grid()
    ax[2].set_xlabel('pressure in Pa')
    ax[2].set_ylabel('rho in kg/m3')
    plt.tight_layout()
    fig.savefig('diagram_' + back_end +'.pdf')
    fig.savefig('diagram_' + back_end +'.png')
```
diagram_IF97
diagram_HEOS

So I went on and tried for the liquid saturation state and tried for a (random) range of enthalpy values. There are a lot of states, where entropy and density have quite large jumps and the values are off a lot from the actual value. I'll only post the code here. If there is something I can do on this, please let me know.

Thank you for your great effort, cheers!

``` python
def plot_data(df, back_end, h):

    fig, ax = plt.subplots(3, 1)

    ax[0].set_title(back_end)
    ax[0].scatter(df.index, df['s'], marker='x')
    ax[0].grid()
    ax[0].set_xlabel('pressure in Pa')
    ax[0].set_ylabel('entropy in J/kgK')
    ax[1].scatter(df.index, df['T'], marker='x')
    ax[1].grid()
    ax[1].set_xlabel('pressure in Pa')
    ax[1].set_ylabel('temperature in K')
    ax[2].scatter(df.index, df['rho'], marker='x')
    ax[2].grid()
    ax[2].set_xlabel('pressure in Pa')
    ax[2].set_ylabel('rho in kg/m3')
    plt.tight_layout()
    fig.savefig('diagram_' + back_end + '_at_' + str(round(h)) + '.pdf')
    fig.savefig('diagram_' + back_end + '_at_' + str(round(h)) + '.png')
    plt.close()


for back_end in ['HEOS', 'IF97']:

    state = CP.AbstractState(back_end, 'water')

    h_min = 0
    T_crit = state.trivial_keyed_output(CP.iT_critical)
    p_triple = state.trivial_keyed_output(CP.iP_triple)
    p_crit = state.trivial_keyed_output(CP.iP_critical)
    p_range = np.geomspace(p_triple, p_crit, 50)

    h_range = {}

    for p in p_range:
        state.update(CP.PQ_INPUTS, p, 0)
        h_range[p] = state.hmass()

    for p_at_h, h in h_range.items():

        p_range_at_h = np.geomspace(p_at_h - 25, p_at_h + 25, 100)
        df = pd.DataFrame(columns=['s', 'T', 'rho'])

        for p in p_range_at_h:
            try:
                state.update(CP.HmassP_INPUTS, h, p)
                df.loc[p, 's'] = state.smass()
                df.loc[p, 'T'] = state.T()
                df.loc[p, 'rho'] = state.rhomass()
            except ValueError:
                df.loc[p, 's'] = np.nan
                df.loc[p, 'T'] = np.nan
                df.loc[p, 'rho'] = np.nan

        plot_data(df, back_end, h)
```

### LINKED ISSUE #2334: PS Input Pair Gives Erroneous Result on Saturation Curve in IF97 Backend
### Description

IF97 Backend reverse calculation using (P, S) delivering erroneous values when state point is on the saturation 
Reporting this issue for a [user of CoolProp with Mathcad and SMath](https://en.smath.com/forum/yaf_postst23768_f-x--y----3D-plot-and-optimal-point.aspx) interfaces.

### Steps to Reproduce

1. Evaluate PropSI("H","P",`<p>`,"S",`<SsatL @ p>`,"IF97::H2O")
2. Any pressure below the critical pressure can be used, <p>
3. Any Output parameter will give the same issue

**Expected behavior:** Liquid saturation point values returned.

**Actual behavior:** **_Vapor_** saturation point values returned.  "Phase" returns "gas_phase" erroneously.

image

### Versions

**CoolProp Version:** Latest (6.6.0)
**Operating System and Version:** Windows 10 
**Access Method:** Mathcad/Python/SMath

### Additional Information

- Probably occurring at the saturated vapor point as well, but since the sat. vapor values are returned, it is not noticeable.
- Probably the same for reverse calculations using (P, H).
- Tracked it down so far to phase determination on the saturation curve, not sure yet if the issue is in the CoolProp backend routine, or in IF97 itself.  A phase determination function from IF97.h does get called to make this determination.

### PR DESCRIPTION
**Pull request by henningjp**
### Description of the Change

IF97 calls with PH or PS inputs (_reverse functions of (P, H) and (P, S)_) were failing to return temperatures (and then other property values) in the correct phase due to (published) uncertainties of ±25 mK in the IF97 reverse temperature equations.  For state points very close to the saturation curve, this would periodically result in temperatures in the opposite phase, on the other side of the saturation curve, resulting in other properties being returned from the wrong phase.  This condition has been fixed in the external IF97 module and tested extensively there outside of CoolProp (see CoolProp/IF97#49).

This change:
1. Bumps the IF97 version in CoolProp to include the patches to IF97.
2. Makes phase determination based on the input PH and PS values rather than the resulting PT at the state point. 

### Benefits

Correct properties are returned from High-Level and Low-Level calls along the saturation curve, including state points that are just off the saturation curve in either the Vapor or Liquid phase.

### Possible Drawbacks

* Can result in slight discontinuities when moving from the liquid phase to two-phase region or from two phase region to vapor phase for Temperature (T) and density (D) as output keys.
* Reverse calls for S with PH inputs, as well as H with PS inputs can result in errors of 0.015% from the forward function values.  This is a result of the uncertainty in the reverse IF97 T(P, H) and T(P, S) functions (documented in the IAPWS-IF97 releases) and not the coding implementation here.
* Specialized reverse functions for H(P, S) and S(P, H) are utilized from IF97 when PS or PH are utilized to remove previously mentioned discontinuities in (T) and (D) at the saturation curves, but carries the above mentioned ±0.015% error into the two-phase region.

### Verification Process

Changes here only affect calls to the IF97Backend and should have no impact on the rest of CoolProp.

- *How did you verify that all new functionality works as expected?*

   The same tests used for the CoolProp/IF97#49 patch were run through both High-Level PropsSI calls (Mathcad Wrapper) and the Low-Level state calls (Python).

- *How did you verify that all changed functionality works as expected?*

   Plots generated utilizing the new H(P, S) and S(P, H) calls generated to show correct values and removal of discontinuity at the phase boundaries (see below).  

- *How did you verify that the change has not introduced any regressions?*

Regression test run from Mathcad regression sheet showing no changes in general functionality.  Low-level calls in Python showing expected behavior in all backends.  IF97 code checked extensively in CoolProp/IF97#49.

### Applicable Issues

Closes #1918 

   Now returns correct temperature, enthalpy, and entropy values from the correct phase as saturation curves are approached, properly dealing with the reverse IF97 function uncertainty. 
  
   image

Closes #2334 

   Now returns correct temperature, enthalpy, and entropy values from the correct phase along the saturation curves.   
   
   image

### CODE REVIEW

**Comment by henningjp** [comment]
Also, Nightly builds haven't run since 2024-1-16?  Did something change on that date?

**Comment by ibell** [comment]
@jowr - any idea?

**Comment by nhenn6** [comment]
Looks like Something Changed in regards to the  emscripten's `--memory-init-file` flag in https://github.com/CoolProp/CoolProp/blob/ae2284e498428d146970bf2fc74f9f46fb973a71/CMakeLists.txt#L1800

Jeff is going to look into it.

**Comment by henningjp** [comment]
I'm going to cancel this PR and try to work on the failing checks.  Will resubmit after.

**Pull request closed without merging**
