### PR TITLE
Coverity scan

### PR DESCRIPTION
**Pull request by jowr**
Use Travis to build and commit a coverity scan. Also includes some of the initial changes from the travis_integration branch.

### CODE REVIEW

**Comment by ibell** [comment]
This is fantastic, thanks for doing it!  

In the future, you might want to squash-merge instead of a merge as it will clean up the fiddle-try-fiddle-try cycle of TravisCI development

**Comment by jowr** [comment]
I did indeed squash-merge, see: https://github.com/CoolProp/CoolProp/commit/44172d1df07fd7aef23c90936e839c2dc381a106

**Comment by ibell** [comment]
Ah yes, of course.  Pardon my inability to read.  Thanks again for figuring out how to set this up, I'm going to grab your coverity code for a couple of other projects I am working on!  Are there any secret tricks I need to know about?

**Comment by jowr** [comment]
No magic involved, just make sure to set the `COVERITY_SCAN_TOKEN` environment variable. If you use Travis, you can encrypt it with the `travis encrypt` command using the project repo's public key. Alternatively, you can visit the `Project Actions->Submit Build->Configure Travis CI` page within the Coverity Scan project and grab your details from there.

**Comment by ibell** [comment]
Cool - thanks for the info.  That will definitely come in handy

**Pull request merged**
