### PR TITLE
Issues/1820

### LINKED ISSUE #1820: Humid air example fails due to new limits
The recently introduced limits for the HAPropsSi cause the examples to fail ungracefully. This should be fixed be fore we release 6.3.0.

### PR DESCRIPTION
**Pull request by ibell**
closes #1820

### CODE REVIEW

**Comment by ibell** [comment]
This works perfectly now: 
Exceptions: 0 / 51894 = 0%
Bad Accuracy: 0 / 51894 = 0%

And much faster too now that I fixed some stupidity about dewpoint inputs.

If you want to run the tests again, that might be wise, but it should be 100% pass rate

**Comment by jowr** [comment]
Great! I am going to fix the Travis builds and add some results to the humid air benchmark code.

**Comment by jowr** [comment]
I changed the T limits and there are still some regions with problems. However, the overall performance and stability has improved a lot! Great work.

See https://travis-ci.org/CoolProp/CoolProp/jobs/523406260 for test logs.

**Comment by ibell** [comment]
I think I'm done with this for now; these humid air routines are a massive time black home.  Does the model even make sense at 130 K and 373 K?  I'd say go ahead and merge.

**Pull request merged**
