### PR TITLE
Fix cxx17

### PR DESCRIPTION
**Pull request by ssg-aero**
### Description of the Change

* Fix lack of  __cplusplus for MSVC adding _MSC_VER check

### CODE REVIEW

**Comment by ibell** [comment]
Can you please rebase your code onto the upstream so that this merge request is a single commit and has a clean diff?

**Comment by ssg-aero** [comment]
Hi, I'm not very familiar with gitHub and I guess I'll need some help for this.
I don't have a clue on how synchronize the fork I've made with you changes.
The only way I've found out is to create a new fork and propose a new PR. I guess there is an other way.

**Comment by ibell** [comment]
One of the developers of CoolProp put together some docs: https://github.com/CoolProp/CoolProp/wiki/Contributing%3A-git-development-workflow

**Comment by ibell** [comment]
Basically, I think you want to merge in the commits from CoolProp/CoolProp, make a new branch with the single commit, and then make a pull request from your new branch to CoolProp/CoolProp.

I admit that even after a decade of the use of git, I find myself sometimes getting totally confused by these sorts of discussions.

**Pull request closed without merging**
