### PR TITLE
Bump IF97 revision

### LINKED ISSUE #1412: Ambiguous abs in IF97Backend
```
FAILED: CMakeFiles/CoolProp.dir/src/Backends/IF97/IF97Backend.cpp.obj
C:\msys64\mingw64\bin\c++.exe   -DCoolProp_EXPORTS -IC:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop -IC:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/externals/Eigen -IC:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/externals/msgpack-c/include -IC:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/externals/cppformat -IC:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/include -IC:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/src -march=x86-64 -mtune=generic -O2 -pipe -O3 -DNDEBUG    -DCOOLPROP_LIB -m64 -MD -MT CMakeFiles/CoolProp.dir/src/Backends/IF97/IF97Backend.cpp.obj -MF CMakeFiles\CoolProp.dir\src\Backends\IF97\IF97Backend.cpp.obj.d -o CMakeFiles/CoolProp.dir/src/Backends/IF97/IF97Backend.cpp.obj -c C:\msys64\home\Engineer46\packages\coolprop-git\src\coolprop\src\Backends\IF97\IF97Backend.cpp
In file included from C:\msys64\home\Engineer46\packages\coolprop-git\src\coolprop\src\Backends\IF97\IF97Backend.h:6:0,
                 from C:\msys64\home\Engineer46\packages\coolprop-git\src\coolprop\src\Backends\IF97\IF97Backend.cpp:1:
C:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/externals/IF97/IF97.h: In function 'double IF97::rho_pX(double, double, IF97parameters)':
C:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/externals/IF97/IF97.h:3974:23: error: call of overloaded 'abs(double)' is ambiguous
         if (abs(T-Tsat) < 1.0E-10){                                // If in saturation dome
                       ^
In file included from C:/msys64/mingw64/include/c++/6.3.0/cstdlib:75:0,
                 from C:/msys64/mingw64/include/c++/6.3.0/ext/string_conversions.h:41,
                 from C:/msys64/mingw64/include/c++/6.3.0/bits/basic_string.h:5402,
                 from C:/msys64/mingw64/include/c++/6.3.0/string:52,
                 from C:/msys64/mingw64/include/c++/6.3.0/bits/locale_classes.h:40,
                 from C:/msys64/mingw64/include/c++/6.3.0/bits/ios_base.h:41,
                 from C:/msys64/mingw64/include/c++/6.3.0/ios:42,
                 from C:/msys64/mingw64/include/c++/6.3.0/ostream:38,
                 from C:/msys64/mingw64/include/c++/6.3.0/iostream:39,
                 from C:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/include/Exceptions.h:7,
                 from C:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/include/CoolPropTools.h:9,
                 from C:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/include/DataStructures.h:11,
                 from C:\msys64\home\Engineer46\packages\coolprop-git\src\coolprop\src\Backends\IF97\IF97Backend.h:5,
                 from C:\msys64\home\Engineer46\packages\coolprop-git\src\coolprop\src\Backends\IF97\IF97Backend.cpp:1:
C:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:338:15: note: candidate: int abs(int)
   int __cdecl abs(int _X);
               ^~~
In file included from C:/msys64/mingw64/include/c++/6.3.0/ext/string_conversions.h:41:0,
                 from C:/msys64/mingw64/include/c++/6.3.0/bits/basic_string.h:5402,
                 from C:/msys64/mingw64/include/c++/6.3.0/string:52,
                 from C:/msys64/mingw64/include/c++/6.3.0/bits/locale_classes.h:40,
                 from C:/msys64/mingw64/include/c++/6.3.0/bits/ios_base.h:41,
                 from C:/msys64/mingw64/include/c++/6.3.0/ios:42,
                 from C:/msys64/mingw64/include/c++/6.3.0/ostream:38,
                 from C:/msys64/mingw64/include/c++/6.3.0/iostream:39,
                 from C:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/include/Exceptions.h:7,
                 from C:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/include/CoolPropTools.h:9,
                 from C:/msys64/home/Engineer46/packages/coolprop-git/src/coolprop/include/DataStructures.h:11,
                 from C:\msys64\home\Engineer46\packages\coolprop-git\src\coolprop\src\Backends\IF97\IF97Backend.h:5,
                 from C:\msys64\home\Engineer46\packages\coolprop-git\src\coolprop\src\Backends\IF97\IF97Backend.cpp:1:
C:/msys64/mingw64/include/c++/6.3.0/cstdlib:185:3: note: candidate: __int128 std::abs(__int128)
   abs(__GLIBCXX_TYPE_INT_N_0 __x) { return __x >= 0 ? __x : -__x; }
   ^~~
C:/msys64/mingw64/include/c++/6.3.0/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
C:/msys64/mingw64/include/c++/6.3.0/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
[32/36] Building CXX object CMakeFiles/CoolProp.dir/src/Tests/TestObjects.cpp.obj
[33/36] Building CXX object CMakeFiles/CoolProp.dir/src/PolyMath.cpp.obj
[34/36] Building CXX object CMakeFiles/CoolProp.dir/src/CoolPropLib.cpp.obj
[35/36] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Incompressible/IncompressibleLibrary.cpp.obj
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by henningjp**
fixes #1412

### CODE REVIEW

**Comment by ibell** [comment]
I think there is something wrong with this PR: http://www.coolprop.dreamhosters.com:8010/builders/Java-OSX/builds/2086/steps/git/logs/stdio

**Comment by ibell** [comment]
Here's how I fixed it:
```
Ians-Mac-mini:coolprop ian$ cd externals/IF97/

Ians-Mac-mini:IF97 ian$ git pull origin master
From https://github.com/CoolProp/IF97
 * branch            master     -> FETCH_HEAD
Updating 7e31cb2..7302870
Fast-forward
 IF97.cpp                                    | 226 ++++++++++++++--------------
 IF97.h                                      | 212 ++++++++++++++------------
 README.md                                   |  23 ++-
 wrapper/Mathcad/README.md                   |   5 +
 wrapper/Mathcad/if97_validation.pdf         | Bin 677523 -> 715424 bytes
 wrapper/Mathcad/if97_validation.xmcdz       | Bin 1157525 -> 1194313 bytes
 wrapper/Mathcad/if97_validation_IAPWS.pdf   | Bin 0 -> 719995 bytes
 wrapper/Mathcad/if97_validation_IAPWS.xmcdz | Bin 0 -> 1218464 bytes
 wrapper/Mathcad/includes/version.h          |   1 -
 9 files changed, 250 insertions(+), 217 deletions(-)
 create mode 100644 wrapper/Mathcad/if97_validation_IAPWS.pdf
 create mode 100644 wrapper/Mathcad/if97_validation_IAPWS.xmcdz
Ians-Mac-mini:IF97 ian$ cd ../..

Ians-Mac-mini:coolprop ian$ git add externals/IF97/
 
Ians-Mac-mini:coolprop ian$ git commit -m "Bump IF97 revision again; see #1415"
```

**Comment by henningjp** [comment]
Hmmm.... Those were **_exactly_** the steps I took.  Not sure what went wrong, other than i did this on my local repo before the IF97 patch was pull in.  Thanks for fixing.

**Comment by oroppas** [comment]
The fix hasn't been reflected in CoolProp/externals when I cloned the repo.

**Comment by ibell** [comment]
You probably need to do a:

git submodule update --init

**Comment by oroppas** [comment]
Hmm, not such luck. It didn't work on Windows (mingw-w64). I'll check on Linux.

**Comment by ibell** [comment]
Or, failing that, a full recursive clone.  You must be doing something
funny, it works fine for me.

**Comment by henningjp** [comment]
@ibell I'm having the same problem.   The CP master on Github is sitting at commit 7302870
cp_externals

But the patch commit on IF97 was commit 58b11f9
if97revisions

7302870 is one commit back.   My PR that I put in today attempts to update this again.  Your "fix" on #1415 should have brought us up-to-date, but didn't quite get us there...

Third time is a charm!

**Comment by oroppas** [comment]
I doesn't seem to be fixed yet. Any luck?

**Comment by henningjp** [comment]
@iball, this loose end is still hanging.  Please address when you're feeling better.  My PR #1428 has a bump revision in it.   I can push it in a separate PR if you'd rather.  Thanks.

**Comment by henningjp** [comment]
@oroppas This should be updated now.

**Comment by oroppas** [comment]
@henningjp Thanks. I see the update.
Now CoolProp can be built on MinGW-w64 environment.

**Pull request merged**
