### PR TITLE
editorconfig

### PR DESCRIPTION
**Pull request by thorade**
Opening the PR so changes can be seen and discussed.
This is for #1254 

Note: This will only help in case a contributor uses one of the editors or IDEs that support editorconfig files.
Adding the file will not change existing code, that would have to be addressed in a different PR.

- What extensions should be covered? (*.sh, *,bat, *.yml)
- Configurations for single files are possible (CMakeLists.txt or travis.yml)
- What parts of editorconfig should be used?

### CODE REVIEW

**Comment by jowr** [comment]
Good start! Just a few comments:

* CMake files have 2 spaces indentation (*.cmake, CMakeListst.txt)
* What about newline characters? That was and probably is one of the biggest issues.

**Comment by henningjp** [comment]
I think python scripts have to have tabs, not spaces, to specify indent levels for loops.  Right?

**Comment by ibell** [comment]
Never tabs in python for indentation!!  The recommendation is 4 spaces
instead of a tab.  All reasonable editors can handle that nowadays

**Comment by henningjp** [comment]
Sorry, @ibell .  My bad.  It was the Makefile that didn't like the spaces when I was building the local docs, not the python scripts.

**Comment by thorade** [comment]
@henningjp For Python there is PEP8 which has rules for almost all formatting:
https://www.python.org/dev/peps/pep-0008/
And there are tools that enforce these rules, like autopep8.

@jowr Regarding newline characters: git converts newline characters upon pulling and pushing. To my understanding, a comprehensive gitattributes file should be sufficient.

**Comment by thorade** [comment]
Here is a list of extensions that appear in the repo, extracted with a small script:
[fileExtensions.txt](https://github.com/CoolProp/CoolProp/files/1531017/fileExtensions.txt)

**Comment by thorade** [comment]
This PR is in a state that it could be merged, it does not break anything and can be enhanced/extended later on.

**Pull request merged**
