### PR TITLE
replace bytestring (deprecated) with unsafe_string

### PR DESCRIPTION
**Pull request by DANA-Laboratory**

### CODE REVIEW

**Comment by ibell** [comment]
Is this change backwards compatible?

**Comment by vimalaad** [comment]
I added a second commit to keep it compatible with older Julia, but I think it is not necessary to hard code this type of version  checking, normally interoperability between older and newer versions of the Julia language done by [Compat.jl](https://github.com/JuliaLang/Compat.jl), so +1 to remove version checking and start using Compat.jl

**Comment by ibell** [comment]
+1 on using Compat.jl from my quick perusal

**Comment by ibell** [comment]
Okie dokie, looks good.  Hopefully we won't get complaints from other julia users.

**Pull request merged**
