### PR TITLE
Added "set_reference_state" wrapper for Mathcad and Updated Example Worksheets

### PR DESCRIPTION
**Pull request by henningjp**
* Added set_reference_stateS() function wrapper
* Added critical example worksheets for both Mathcad 15 and Prime (plus PDFs of each viewable for not Mathcad users).
* Tidies up README formatting

### CODE REVIEW

**Comment by henningjp** [comment]
I give up.  I don't understand why these old commits are coming with the PR.  :unamused: 
- [x] I created a branch from the local master
- [x] I made two commits
- [x] I pushed to my fork
- [x] Issued the pull request

Somebody please help me understand what I'm doing wrong.  :weary:

**Comment by ibell** [comment]
I think maybe you need to rebase your fork against our master before you
branch?  That might kill off the the merges.  It's not a big problem in
reality though, since I'm going to squash merge the branch anyway.  And
that will ignore all the merges.  So no worries.

**Comment by ibell** [comment]
CMakeLists.txt still has conflicted code in it...

**Comment by henningjp** [comment]
@ibell something weird happened to CMakeLists.txt when I merged from CoolProp/master.  I had some funky lines in it.

**Comment by ibell** [comment]
Please correct them and I will merge the PR.

**Comment by henningjp** [comment]
I don't see this conflict in my local repository.  Not sure how to fix it.  A little help?

**Comment by ibell** [comment]
Can you give me write access to your fork?  I can tidy it up...

**Comment by henningjp** [comment]
Did that fix it?

**Comment by ibell** [comment]
Seems to have...

**Comment by ibell** [comment]
Merging...

**Comment by henningjp** [comment]
You'll want to check you buildbot again to make sure I didn't screw up CMakeList.txt  It compiles ok here, but you never know...

**Comment by ibell** [comment]
Looks fine, only change is whitespace.  I'll get 100 emails if there is a
problem in CMakeLists.txt :)

**Comment by henningjp** [comment]
Line 456 should be changed from "CoolPropFluidProperties.xmcd" to "CoolPropFluidProperties.xmcdz".  I switched file types in the directory - this is a compressed file type that Mathcad uses and is about half the size.  You're install command won't find the .xmcd file anymore.

**Comment by ibell** [comment]
I'll fix it. Good to have a smaller file in there....

**Pull request merged**
