### PR TITLE
Github Actions: add shared library and doxygen workflows.

### PR DESCRIPTION
**Pull request by jmarrec**
Reacting to a comment on https://github.com/CoolProp/CoolProp/pull/2097#issuecomment-1067484987

@ibell  I honestly don't know if that's what you had in mind or not, and I definitely don't understand what the "Installer package" is supposed to be, is that the `COOLPROP_WINDOWS_PACKAGE` ?

Anyways, this will build the shared lib, and package it up nicely in a version-named tar.gz, uploaded as an artifact.
If you trigger a release (via github, but that effectively creates a tag which is the actual trigger), it will also upload them to the release page.

The HTML version of the documentation is also packaged in a tar.gz and has the same upload treatment. Not sure if that's what you needed either.

---

**Edit**:

- Windows isntaller package, checkout this run: https://github.com/jmarrec/CoolProp/actions/runs/1985940859
```
CoolProp-6.4.2-dev-WindowsInstaller.tar.gz
├── Installers
│   └── Windows
│       └── CoolProp_v6.4.2.0.exe
└── MicrosoftExcel
    ├── CoolProp.xla
    ├── CoolProp.xlam
    └── TestExcel.xlsx

3 directories, 4 files
```

- Checkout this release on my fork, to showcase the upload of artifacts to the release page: https://github.com/jmarrec/CoolProp/releases/tag/v6.4.2-dev

Screen Shot 2022-03-15 at 11 42 35

### CODE REVIEW

**Comment by jmarrec** [comment]
I guess perhaps uploading the Windows installer .exe directly to the release page makes more sense?
What about the Excel stuff though?

**Comment by ibell** [comment]
I had in mind the last few shared library options from http://www.coolprop.dreamhosters.com:8010/grid

**Comment by ibell** [comment]
Would it be feasible to build 32-bit DLL? If not, I can live with that - 64-bit is now the standard.

**Comment by ibell** [comment]
Yep, this is the installer package - you're amazing!  Do you want to dig into the C++? We really need someone to.

**Comment by jmarrec** [comment]
@ibell I added a workflow to run the catch2 tests. Many are failling. Some are failing because of missing Refprop. I have tried to built it locally from https://github.com/usnistgov/REFPROP-cmake but it fails to work due to PASS_FNT.FOR when I use the instructions.

**Pull request merged**
