### PR TITLE
Documentation Update

### LINKED ISSUE #1501: Building Documentation
Several issues here when trying to build the documentation:

1. Should the [instructions](http://www.coolprop.org/develop/documentation.html) (minus step 0. for mac OS) work on Windows using Anaconda?  Has this been done?  I got it to work, sort of, but with much jumping through hoops and it doesn't all build correctly.  I had to fetch many 64-bit versions of the requisite modules and install the wheel files manually.  There's still some weird error at the beginning of the build about matplotlib calls being out of order.

2. There is a serious problem with converting the fluid_properties/mixtures.rst file.  This one is not just me.  Check out the [mixtures page](http://www.coolprop.org/dev/fluid_properties/Mixtures.html) on the CoolProp/dev documentation.  Something going wrong here in the ipython examples and this happens throughout the picture.  @ibell made a commit to this .rst file in the offending area some time back, but I don't think this is causing the errors.  ipython seems to think that binary pair data for 'Helium' and 'Xenon' already exist; yet when I run these scripts manually in Anaconda, they run fine.

3. Another error occurs that floods the stdout with messages and I can't capture where it is coming from.  It looks, though, like an example is trying to generate plots and it is calling flash routines with input parameters that are out of bounds.  See sample message below:

    c:\program files\anaconda2\lib\site-packages\CoolProp\Plots\Common.py:622: UserWarning: An error occurred for inputs 210905.712095, 3269.231633 with index (206L,): HmolarSmolar: [HSFLSH error 200] h-s inputs are two-phase or out of bounds, iterative routine is not available to find a solution.   

    You have to do a clean build (make clean html) to get these error message to print.

4. Lots of errors for missing .csv and tag files that it can't find as well as a couple of include files.

5. Oh yeah, and : **WARNING: logo file '_static/CoolPropLogo.png' does not exist**  This is easy to fix, but shouldn't it be in _static/  on the repository?

### PR DESCRIPTION
**Pull request by henningjp**
This is strictly a Documentation update (closes #1501 ). Changes include:

- [x] Added misc ignores so dynamic doc content can be built in repository
- [x] Update to documentation Makefile for clean html build on Windows
- [x] Updates to instructions for doc builds on Windows with Anaconda (includes suggestions from @jowr)
- [x] Added documentation page for IF97
- [x] Fixed errors on documentation page for Fluid_Properties/Mixtures
- [x] Updated HighLevelAPI doc page to include a section on calculating Vapor, Liquid, Saturation states (including latent heat calculation) that may head off some common new user questions.
- [x] Updated some print commands so docs can be built on Python 2 or 3
- [x] Updated documentation to compile the Python wrapper on Windows

This is a clean PR that replaces #1547 that got too far out of date.  @ibell & @jowr there are only minor changes from what you looked at before.  Because of the various areas affected, not sure if you want this to be "squashed" or maintain the separate commits as a documentation trail.

### CODE REVIEW

**Comment by henningjp** [comment]
@jowr , Any idea why the Scrutinizer is failing?  These are just .rst and .ignore files.  The scheduled scrutinization looks like it for some reason can't pull over the source files?  Not sure.

**Comment by jowr** [comment]
No, the logs do not really say much...

**Comment by henningjp** [comment]
@jowr Can I merge it anyway?

**Comment by henningjp** [comment]
@jowr Do the /dev docs not get built nightly?  Or are we having buildbot issues?  I'm not seeing these updates.

**Comment by ibell** [comment]
There's something amiss in the MATLAB wrapper that gets built as part of
the build. I'm trying to debug what is up with that.  Maybe I'll just
disable the MATLAB part.

**Comment by ibell** [comment]
Or actually, I am going to convert the MATLAB part to use python, and I
just need to rewrite a little bit the MATLAB example generator.

**Comment by ibell** [comment]
I just turned off the MATLAB stuff.  At some point I should convert it over
to using python.

**Comment by henningjp** [comment]
👍

**Pull request merged**
